Revert "Fixup: assign host port manually if not find for vnc, migration"
This reverts commit 24e4d5c690979d5a243ba34188ff46b702f936cb.

we hit below issue.

   File "/usr/local/lib/python3.8/site-packages/virttest/qemu_vm.py", line 2207, in make_create_command
     cmd += add_vnc(self.vnc_port, vnc_password, vnc_extra_params)
   File "/usr/local/lib/python3.8/site-packages/virttest/qemu_vm.py", line 810, in add_vnc
     vnc_cmd = " -vnc :%d" % (vnc_port - 5900)
 TypeError: unsupported operand type(s) for -: 'list' and 'int'